name: ci

on:
  push:
    branches: master

jobs:
  login:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        run: |
          env | sort
          t=ghcr.io/$GITHUB_REPOSITORY
          date=`date +%Y%m%d`
          docker build --tag $t:latest --tag $t:$date .
      - name: Push Docker image
        run: |
          docker push ghcr.io/$GITHUB_REPOSITORY:latest
          docker push ghcr.io/$GITHUB_REPOSITORY:`date +%Y%m%d`
